### ISSUE TITLE
Same values.

### ISSUE THREAD

**Issue by djmbritt** [UnravelTEC/Raspi-Driver-SPS30#1]
Is it normal to have the same values for pm2.5, pm4 and pm10?

**Comment by species** [comment]
Yes, this is perfectly normal.

The pm* values (µg/m³) are summed up - pm10 is every particle <10µm, pm4 is every particle <4µm, etc. If e.g. there are no particles > 2.5µm, pm2.5 - pm10 are the same.

**Comment by djmbritt** [comment]
So, if I wanted to get a good idea of how much there is in each range I would have to subtract pm4 from pm10 for example.

**Comment by species** [comment]
exactly.

**Comment by djmbritt** [comment]
Thanks :+1:
