### ISSUE TITLE
I2C write failed

### ISSUE THREAD

**Issue by smiles2019** [UnravelTEC/Raspi-Driver-SPS30#2]
I tried several times on different raspberry pi but ended up in following two results each time :
either
RESULT 1: . 
I2Cdetect found SPS30
error()
error in i2c_write: pigpio module exception: I2C write failed
readFromAddr: write try unsuccessful, next
error()
error in i2c_write: pigpio module exception: I2C write failed
readFromAddr: write try unsuccessful, next
error()
error in i2c_write: pigpio module exception: I2C write failed
readFromAddr: write try unsuccessful, next
readFromAddr: write tries(3) exceeded
readArticleCode failed
RESULT 2 :
I2Cdetect found SPS30
Article code: ""
Serial number: 3-1-7-B-9-6-6-0-8-E-0-9-8-7-9-0
cleaning interval: 345600 s

**Comment by species** [comment]
SPS30 is picky on the i2c on Raspberry... could you anwer the following questions:

- which i2c bus are you using?
- which i2c frequency are you using?
- are there any other i2c devices on your bus?
- how long are your cables?
- do you use any extra pullups?

**Comment by species** [comment]
we figured out the SPS30 only works reliably when:
* using i2c-1
* no other i2c devices are present on the same bus.
