### ISSUE TITLE
SPS30 hanging

### ISSUE THREAD

**Issue by senisioi** [UnravelTEC/Raspi-Driver-SPS30#5]
I just installed everythin as you mentioned and my SPS30 stays hanging with this output:
```
I2Cdetect found SPS30
Article code: ""
Serial number: C-B-8-9-C-E-D-A-C-F-9-3-1-0-3-F
cleaning interval: 604800 s
```
Do you have any clue what might cause this?

**Comment by Back-Pack-Jack** [comment]
> I just installed everythin as you mentioned and my SPS30 stays hanging with this output:
> 
> ```
> I2Cdetect found SPS30
> Article code: ""
> Serial number: C-B-8-9-C-E-D-A-C-F-9-3-1-0-3-F
> cleaning interval: 604800 s
> ```
> 
> Do you have any clue what might cause this?

The sensor is writing to a file in '/run/sensors/sps30' named 'last'
If you uncomment line : 254 in  'sps30-service.py' the device will print to the terminal

**Comment by species** [comment]
It is the intended behaviour that there is no output on the terminal after startup.

Sensor data gets written periodically to the file /run/sensors/sps30/last - to be scraped by the Prometheus database.
