### ISSUE TITLE
Help understanding data

### ISSUE THREAD

**Issue by okor** [UnravelTEC/Raspi-Driver-SPS30#6]
Thank you for the library! Seems to work very well. Though I'm trying to understand the data reported.

Without modification to your code, I get the following from the log file:
```
particulate_matter_ppcm3{size="pm0.5",sensor="SPS30"} 13215.14453125
particulate_matter_ppcm3{size="pm1",sensor="SPS30"} 15053.44238281
particulate_matter_ppcm3{size="pm2.5",sensor="SPS30"} 15088.30566406
particulate_matter_ppcm3{size="pm4",sensor="SPS30"} 15093.20410156
particulate_matter_ppcm3{size="pm10",sensor="SPS30"} 15095.94140625
particulate_matter_ugpm3{size="pm1",sensor="SPS30"} 1890.56481934
particulate_matter_ugpm3{size="pm2.5",sensor="SPS30"} 1999.20068359
particulate_matter_ugpm3{size="pm4",sensor="SPS30"} 1999.19812012
particulate_matter_ugpm3{size="pm10",sensor="SPS30"} 1999.20068359
particulate_matter_typpartsize_um{sensor="SPS30"} 0.28011751
```

A PM2.5 of 1999.20068359 is ... really bad. I expected to see numbers ranging from 0 to 500'ish which I based on the [published standards from the American EPA](https://www.epa.gov/pm-pollution/national-ambient-air-quality-standards-naaqs-pm). The room this thing is being tested in seems quite clean (though not a "clean room"), with significantly sized air purifiers w/pre-filter,carbon,HEPA filters. 

Here's a reading from outside:
```
particulate_matter_ppcm3{size="pm0.5",sensor="SPS30"} 3844.33666992
particulate_matter_ppcm3{size="pm1",sensor="SPS30"} 4379.10498047
particulate_matter_ppcm3{size="pm2.5",sensor="SPS30"} 4389.24658203
particulate_matter_ppcm3{size="pm4",sensor="SPS30"} 4390.67138672
particulate_matter_ppcm3{size="pm10",sensor="SPS30"} 4391.46777344
particulate_matter_ugpm3{size="pm1",sensor="SPS30"} 549.97259521
particulate_matter_ugpm3{size="pm2.5",sensor="SPS30"} 581.57519531
particulate_matter_ugpm3{size="pm4",sensor="SPS30"} 581.57446289
particulate_matter_ugpm3{size="pm10",sensor="SPS30"} 581.57519531
particulate_matter_typpartsize_um{sensor="SPS30"} 0.28047669
```

A PM2.5 of 581 outside is also really bad. Much higher than I expected.

From the EPA:
> Currently, the EPA has primary and secondary standards for PM2.5 (annual average standards with levels of 12.0 µg/m3 and 15.0 µg/m3, respectively; 24-hour standards with 98th percentile forms and levels of 35 µg/m3) and PM10 (24-hour standards with one-expected exceedance forms and levels of 150 µg/m3). 

Questions:
- Am I misinterpreting the data? Perhaps those values are sums for a given time period?
- The sensor is a couple of months old but with only a couple of minutes use. That said, could there be something wrong with the sensor?
- Assuming I am misinterpreting the data, how should I be interpreting the data?

I'm sure I'm just making a silly mistake and really appreciate your help. Thank you

**Comment by species** [comment]
Hi okor,

as your readings:
* particle number count is nearly the same across the particle size ranges
* the pm values are very near the 2000-mark

I can rule out a data transmission error and only assume that your sensor is broken (unless you are currently surrounded by forest fires). Normal readings are somewhere in the range of 0.5 - 50 for pm2.5, usually.

Do you have some canned air (or CO₂, it doesn't matter) available? Try put the sensor in a plastic bag, and "rinse" it with a clean gas, what do the readings say?

The only thing I can advise is to call Sensirion support for a replacement.

**Comment by okor** [comment]
@species The sensor and code are perfect, it was my fault. I just needed to add a couple of pullup resistors. Sensirion documented this quite well in the [SPS30 datasheet](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/9.6_Particulate_Matter/Datasheets/Sensirion_PM_Sensors_Datasheet_SPS30.pdf) (which I originally missed). My bad 😊 
![Screen Shot 2021-07-28 at 1 34 07 PM](https://user-images.githubusercontent.com/142910/127384726-1c9a4ca9-473f-4a1a-9b71-ee49288ad3e8.png)

After adding some pull up resistors, the data is as expected:
```
particulate_matter_ppcm3{size="pm0.5",sensor="SPS30"} 5.17253828
particulate_matter_ppcm3{size="pm1",sensor="SPS30"} 6.11591148
particulate_matter_ppcm3{size="pm2.5",sensor="SPS30"} 6.28382683
particulate_matter_ppcm3{size="pm4",sensor="SPS30"} 6.31551600
particulate_matter_ppcm3{size="pm10",sensor="SPS30"} 6.32073927
particulate_matter_ugpm3{size="pm1",sensor="SPS30"} 0.78863692
particulate_matter_ugpm3{size="pm2.5",sensor="SPS30"} 0.99050218
particulate_matter_ugpm3{size="pm4",sensor="SPS30"} 1.11719954
particulate_matter_ugpm3{size="pm10",sensor="SPS30"} 1.14254034
particulate_matter_typpartsize_um{sensor="SPS30"} 0.69291037
```

Thank you for your time and code
